### ISSUE TITLE
Try MultilingualPress

### ISSUE THREAD

**Issue by jacboy** [Neochic/Woodlets#4]
As discussed on WordPress Meetup Stuttgart on 14th of Dec. 2016, here's the thing you should test for multilingualism.

https://de.wordpress.org/plugins/multilingual-press/

**Comment by cstickel** [comment]
Seems to work fine. However the "Advanced translator" feature needs to be disabled.

**Comment by cstickel** [comment]
Updated ["Multilanguage" section](https://github.com/Neochic/Woodlets/blob/master/docs/i18n.md)  of the docs to document the "Advanced translator" incompatibility to MultilingualPress.
